# nginx proxy address - http://172.17.0.1:3000

name: umami
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  app:
    image: ghcr.io/umami-software/umami:postgresql-latest
    container_name: umami-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
    ports:
      - '172.17.0.1:3000:3000'
    volumes:
      - './rootfs/data/umami:/data'
    networks:
      - umami

networks:
  umami:
    name: umami
    external: false
